TILE_SIZE = 40

CANT_COLS = 100
TILE_EMPTY = 0
TILE_COMMERCIAL = 1
TILE_POLICE_DEPARTMENT = 2
TiLE_HOSPITAL = 3
TILE_POWER_PLANT = 5
TILE_STREET = 4
TILE_STREET_CURVE = 6
TILE_STREET_TRIPLE_CURVE = 7
TILE_STREET_CUADRUPLE_CURVE = 8
TILE_TRANSPARENT = 9

ROTATION_LEFT_RIGHT =   0
ROTATION_UP_DOWN =      90
ROTATION_270 =          270
ROTATION_45 =          45
